# Killshot - Magdalena Bay
GET https://cs361-spotify-plays.herokuapp.com/songuri/2tdNI4jmNQkOT41LSTSA17 

###

# Humble - Kendrick Lamar
GET https://cs361-spotify-plays.herokuapp.com/songuri/7KXjTSCq5nL1LoYtL7XAwS
