# Killshot - Magdalena Bay
GET https://spotify-track-popularity.onrender.com/track-uri/2tdNI4jmNQkOT41LSTSA17 

###

# Humble - Kendrick Lamar
GET https://spotify-track-popularity.onrender.com/track-uri/7KXjTSCq5nL1LoYtL7XAwS
